project:
  type: book
  output-dir: _book

book:
  title: "<img src='images/logo.png' width='100%' height='auto' /><br/> IMPT — Índice Multidimensional e Multimodal de Pobreza nos Transportes<br/>"
  favicon: "images/icon.ico"
  subtitle: "Methodological Report"
  author: "U-Shift Lab, Instituto Superior Técnico"
  date: today
  date-format: "MMMM YYYY"
  chapters:
    - index.qmd
    - part: "**Data**"
      chapters:
        - data_sources.qmd
        - data_access.qmd
        - data_preparation.qmd
        - transport_routing.qmd
    - part: "**Dimensions and PCA**"
      chapters:
        - mobility.qmd
        - accessibility.qmd
        - affordability.qmd
        - safety.qmd
        - calculator.qmd
    - part: "**Dashboard and Reproducibility**"
      chapters:
        - output_dashboard.qmd
        - reproducibility.qmd
    - references.qmd
    - about.qmd
  appendices:
    - metadata.qmd
    - pca_results.qmd
  sidebar:
    tools:
    - icon: github
      href: https://github.com/U-Shift/IMPT-data/
      text: "GitHub Repository"
      target: _blank
    - icon: map-fill
      href: https://ushift.pt/apps/impt
      text: "Interactive Dashboard"
      target: _blank
  page-footer:
    left: "U-Shift Lab, Instituto Superior Técnico "
    center: "&copy; 2026, U-Shift, CERIS, Instituto Superior Técnico, University of Lisbon"
    right: "April 2026"
    

bibliography: references.bib

format:
  html:
    theme:
      light: cosmo
      dark: superhero
    toc: true
    number-sections: true
    echo: false
    code-fold: true
    lightbox: true # abrir imagens popup

google-scholar: true