---
title: "Global"
output: html_document
---


```{r}
library(sf)
library(dplyr)
```

# Geographical boundaries

## Districts

```{r}
metadata_districts = readRDS("/data/IMPT/mqat/Metadata_Freguesias.Rds")
metadata_districts

districts = st_read("/data/IMPT/mqat/FREGUESIASgeo.gpkg") |> # https://github.com/U-Shift/MQAT/raw/refs/heads/main/data/IMPT/Metadata_Freguesias.Rds
  left_join(metadata_districts |> select(Dicofre, Freguesia), by="Dicofre")
# mapview::mapview(districts, zcol="Concelho")

```

## Municipalities

```{r}
municipalities = st_read("/data/IMPT/mqat/MUNICIPIOSgeo.gpkg") # https://github.com/U-Shift/MQAT/raw/refs/heads/main/geo/MUNICIPIOSgeo.gpkg
# mapview::mapview(municipalities)
```

## Grid 

```{r}
# Read shapefile at /data/IMPT/BaseDados_PMMUS/Grelha/GrelhaHexagAML/GrelhaHexagAML.shp 
grid_hex = st_read("/data/IMPT/BaseDados_PMMUS/Grelha/GrelhaHexagAML/GrelhaHexagAML.shp")
# View(grid_hex |> sf::st_drop_geometry())
# mapview::mapview(grelha_hex)

grid_hex_pop = st_read("/data/IMPT/BaseDados_PMMUS/2-OcupaçãoTerritório/2.1 - DinâmicasDemográficas.gpkg", layer="Grelha_hexag_amL_pop-2021")
View(grid_hex_pop |> sf::st_drop_geometry())

# left_join(grid_hex_pop |> select(ID, N_INDIVIDU) |> sf::st_drop_geometry(), by=c("id"="ID"))
```